# Generated by Django 5.2.7 on 2025-10-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='nombre',
        ),
    ]
