# Generated by Django 5.2.7 on 2025-10-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(default='', max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(blank=True, default='sin_imagen.png', upload_to='')),
            ],
        ),
    ]
